# Generated by Django 5.2.9 on 2026-01-07 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('category_warning', 'Category Budget Warning'), ('category_exceeded', 'Category Budget Exceeded'), ('budget_warning', 'Total Budget Warning'), ('budget_exceeded', 'Total Budget Exceeded'), ('trend_alert', 'Spending Trend Alert'), ('month_end_summary', 'Month End Summary')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('is_read', models.BooleanField(default=False)),
                ('month', models.DateField(blank=True, help_text='Related month if applicable', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'), models.Index(fields=['user', 'notification_type'], name='core_notifi_user_id_aa1102_idx')],
            },
        ),
    ]
