# Generated by Django 5.2.9 on 2026-01-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(default='BDT', max_length=8),
        ),
    ]
