# Generated by Django 5.2.9 on 2026-01-05 07:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='Use the first day of the month, e.g. 2026-01-01')),
                ('scope', models.CharField(choices=[('overall', 'Overall'), ('category', 'Category')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rollover_enabled', models.BooleanField(default=False)),
                ('warn_threshold', models.DecimalField(decimal_places=3, default=Decimal('0.800'), max_digits=4)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='categories.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(fields=('created_by', 'month', 'scope', 'category'), name='uniq_budget_per_user_month_scope_category')],
            },
        ),
    ]
